# Generated by Django 4.0.4 on 2022-05-24 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_translate', models.CharField(max_length=50, verbose_name='Название статьи на английском')),
                ('title', models.CharField(max_length=50, verbose_name='Название статьи')),
                ('author', models.CharField(max_length=25, verbose_name='Автор')),
                ('summary', models.CharField(max_length=250, verbose_name='Краткое содержание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('num_of_views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('favorites', models.BooleanField(default=False, verbose_name='В избранном')),
                ('my_mark', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)], verbose_name='Моя оценка')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
